# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (3)
# #########################################################################

class CalculatorAPI(BaseModel):
    intent: typing.Optional[str] = None
    operation: typing.Optional[typing.Union[str, str, str, str]] = None
    numbers: typing.List[float]

class Fact(BaseModel):
    value: typing.Optional[int] = None
    units: typing.Optional[str] = None
    start_date: typing.Optional[str] = None
    end_date: typing.Optional[str] = None
    location: typing.Optional[str] = None

class FilingInformation(BaseModel):
    company: typing.Optional[str] = None
    description: typing.Optional[str] = None
    derivation: typing.Optional["Fact"] = None
    facts: typing.List["Fact"]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
