# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.CalculatorAPI": types.CalculatorAPI,
    "stream_types.CalculatorAPI": stream_types.CalculatorAPI,

    "types.Fact": types.Fact,
    "stream_types.Fact": stream_types.Fact,

    "types.FilingInformation": types.FilingInformation,
    "stream_types.FilingInformation": stream_types.FilingInformation,


}