# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (3)
# #########################################################################

class CalculatorAPI(BaseModel):
    intent: typing_extensions.Literal['basic_calculator']
    operation: typing.Union[typing_extensions.Literal['add'], typing_extensions.Literal['subtract'], typing_extensions.Literal['multiply'], typing_extensions.Literal['divide']]
    numbers: typing.List[float]

class Fact(BaseModel):
    value: int
    units: str
    start_date: str
    end_date: typing.Optional[str] = None
    location: typing.Optional[str] = None

class FilingInformation(BaseModel):
    company: str
    description: str
    derivation: typing.Optional["Fact"] = None
    facts: typing.List["Fact"]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
